#!/bin/bash
# <=====================================================>

#   ██████╗ ███████╗ █████╗ ██████╗ ███╗   ███╗███████╗
#   ██╔══██╗██╔════╝██╔══██╗██╔══██╗████╗ ████║██╔════╝
#   ██████╔╝█████╗  ███████║██║  ██║██╔████╔██║█████╗
#   ██╔══██╗██╔══╝  ██╔══██║██║  ██║██║╚██╔╝██║██╔══╝
#   ██║  ██║███████╗██║  ██║██████╔╝██║ ╚═╝ ██║███████╗
#   ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═════╝ ╚═╝     ╚═╝╚══════╝

# <=====================================================>
#      Image Convolution Benchmark README Generator
# <=====================================================>
#  Script directory
# <=====================================================>
WKDIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
# <=====================================================>
#  Configuration
# <=====================================================>
INPUT_DIR="${WKDIR}/../input"
OUTPUT_DIR="${WKDIR}/../output"
OUTPUT_FILE="${WKDIR}/../README.md"
PAGES_LINK="Stefano-UA.github.io/QOL_Study"
# <=====================================================>
#  Check if directories exist
# <=====================================================>
if [ ! -d "$INPUT_DIR" ] || [ ! -d "$OUTPUT_DIR" ]; then
    echo "Error: Directory '${INPUT_DIR}' or '${OUTPUT_DIR}' not found."
    exit 1
fi
# <=====================================================>
#  1. Write Header & Introduction
# <=====================================================>
cat > "$OUTPUT_FILE" <<EOF
# Image Convolution Benchmark

<div align="center">
    <img src="https://img.shields.io/badge/C%2B%2B-23-blue.svg" />
    <img src="https://img.shields.io/badge/SIMD-AVX--512-yellow.svg" />
    <img src="https://img.shields.io/badge/SIMD-AVX2-orange.svg" />
    <img src="https://img.shields.io/badge/SIMD-AVX-red.svg" />
    <img src="https://img.shields.io/badge/SIMD-SSE4.1-lightgrey.svg" />
    <img src="https://img.shields.io/badge/License-GPLv3-green.svg" />
</div>

High-performance implementation of image convolution kernels in C++23. This project serves as a benchmark for CPU computational power, specifically targeting SIMD (Single Instruction, Multiple Data) optimizations using AVX512, AVX2, AVX, and SSE4.1 (x86) instructions.

### Live Demo
Browse the processed image gallery and compare different kernels here:

[**Image Convolution Gallery**](https://${PAGES_LINK})

---

## Index

- [Repository Structure](#repository-structure)
- [Project Objectives](#project-objectives)
- [How to Use](#how-to-use)
- [Visual Analysis](#visual-analysis)
- [Kernel Results](#kernel-results)

---

## Repository Structure

- ./**assets**: Repository assets, including testing verification images.
- ./**build**: Compiled binaries and intermediate build files.
- ./**include**: Header files containing the core logic.
    - /*config.hpp*: Global configuration and benchmark macros.
    - /*convolution.hpp*: Main convolution engine with SIMD specializations.
    - /*simd_ops.hpp*: Abstraction layer for x86 SIMD intrinsics.
    - /*tensor.hpp*: 3D data structure for image representation.
- ./**input**: Source images for benchmarking.
- ./**lib**: External single-header libraries (stb_image).
- ./**output**: Results generated by different convolution kernels.
- ./**scripts**: Automation and utility scripts.
    - /*benchmark.sh*: Orchestrates performance tests.
    - /*test.sh*: Runs the validation suite.
    - /*readme.sh*: The script generating this file.
- ./**src**: Source code implementation.
    - /*main.cpp*: Application entry point and CLI logic.
- ./**visuals**: Python-based performance analysis tools.
- ./**web**: Source files for the GitHub Pages static site.

---

## Project Objectives

- **Performance**: Evaluate CPU throughput using custom SIMD-accelerated kernels.
- **EIS Flexibility**: Support multiple x86 Instruction Set Architectures (AVX2, AVX, SSE4.1) via a unified intrinsic abstraction layer.
- **Type Safety**: Leverage C++ templates and concepts to ensure robust support for different pixel data types.
- **Flag Analysis**: Analyse the impact of different compiler flags and different compiler flags combinations.
- **Vectorization Impact Analysis**: Implement different convolution algorithms with and without vectorization to analse its impact on performance.
- **Visual Verification**: Compare processed results against original inputs to ensure algorithm correctness.

---

## How to Use

### Compilation
The project requires a C++23 compliant compiler (GCC 13+ or Clang 16+).

\`\`\`bash
# Build the project
make -j\$(nproc)
\`\`\`

### Execution
Run the benchmark across all available kernels and inputs:

\`\`\`bash
# Run convolution correctness tests (-O3 binaries only)
./scripts/test.sh

# Run performance benchmarks and collect data (benchmarks.csv)
./scripts/benchmark.sh
\`\`\`

---

## Visual Analysis

The project includes a suite of Python scripts located in \`./visuals\` to visually analyze execution time, cycle counts, and scaling across different optimization flags.

> [!NOTE]
> Detailed plots and interactive charts are generated locally during the benchmarking process. These are used to visually verify hardware performance scaling.

---

## Kernel Results

The following sections showcase the visual impact of each implemented convolution kernel.

EOF
# <=====================================================>
#  2. Generate Kernel Tables
# <=====================================================>
for kernel_dir in "$OUTPUT_DIR"/*; do
    [ -d "$kernel_dir" ] || continue
    kernel="$(basename "$kernel_dir")"
    # Pretty-print kernel name (replace underscores with spaces and capitalize)
    pretty_name=$(echo "$kernel" | sed 's/_/ /g' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) lc(substr($i,2))} function lc(s){return tolower(s)} 1')
    echo "Processing: $pretty_name"
    cat >> "$OUTPUT_FILE" <<EOF

### Kernel: ${pretty_name}
<details>
<summary>Click to expand results</summary>

| Original | Processed |
| :---: | :---: |
EOF
    # Limit to 5 examples per kernel to keep the README size manageable
    count=0
    for image in "$kernel_dir"/*; do
        [ -f "$image" ] || continue
        [ $count -ge 5 ] && break
        filename="$(basename "$image")"
        # Look for matching input image
        orig_path=""
        for ext in jpg jpeg png bmp; do
            if [ -f "${INPUT_DIR}/${filename%.*}.${ext}" ]; then
                orig_path="./input/${filename%.*}.${ext}"
                break
            fi
        done
        if [ -n "$orig_path" ]; then
            rel_output="./output/${kernel}/${filename}"
            echo "| <img src=\"${orig_path}\" width=\"400\" /> | <img src=\"${rel_output}\" width=\"400\" /> |" >> "$OUTPUT_FILE"
            ((count++))
        fi
    done
    echo "</details>" >> "$OUTPUT_FILE"
done
# <=====================================================>
#  3. Write Footer
# <=====================================================>
cat >> "$OUTPUT_FILE" <<EOF

---
*README automatically generated on $(date -u +"%Y-%m-%d %H:%M:%S") UTC*
EOF
echo "Success: README.md updated."